posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.PostList.as_view(), name='index'),
    path('profile', views.my_profile, name='profile'),
    path('create_post', views.create_post, name='create_post'),
    path('create_user', views.create_user, name='create_user'),
    path('login', views.login_user, name='login'),
    path('password_change', views.change_password, name='change_password'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('posts/edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('edit_user', views.edit_profile, name='edit_user'),
    path('user_profile', views.create_userprofile, name='establish_profile'),
    path('post/view_profile/<int:pk>', views.View_Profile.as_view(), name='view_profile'),
    path('edit_profile', views.edit_profilepic, name='edit_profilepic'),   
    path('posts/delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    path('succeed_edit_post', views.succeed_edit_post, name='succeed_edited'),
    path('pump_detail/<int:pk>', views.pump, name='pumped_detail'),
    path('logout', views.logout_user, name='logout'),
    path('post/<int:pk>', views.PostDetail.as_view(), name='post_detail'),


]

scrap_post/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('d0oai32492384h2hdiea674t2qeyrgh2w63427/', admin.site.urls),
    path('', include('posts.urls')),
    path('s3direct/', include('s3direct.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_view.PasswordResetView.as_view(template_name='posts/password_change/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='posts/password_change/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_view.PasswordResetCompleteView.as_view(template_name='posts/password_change/password_reset_complete.html'), name='password_reset_complete'),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import scrap_post.settings as scrapsettings
from django.template.defaultfilters import slugify
from django.urls import reverse
from uuid import uuid4
import os

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
)

Flags = (
    (0, 'saved'),
    (0, 'report'),
)

GENDER = (
    (0, 'male'),
    (1, 'female'),
    (2, 'other'),
)
def user_profilepic_path(instance, filename):
    return '{0}/{0}'.format(instance.user.id,images_path(filename))


class ScrapUser(AbstractUser):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'ScrapUser'
        unique_together = ('email',)

class Profile(models.Model):
    user = models.OneToOneField(ScrapUser, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(upload_to=user_profilepic_path, null=True, blank=True, default='')
    status = models.IntegerField(choices=GENDER, default=0)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, null=True)
    def __str__(self):
        return str(self.user)

    
    def get_gender_name(self):
        return dict(GENDER).get(self.gender)    

def images_path(path):
    def wrapper(instance, filename):
        ext = filename.split('.')[-1]

        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            filename = '{}.{}'.format(uuid4().hex, ext)
        return os.path.join(path, filename)
    return wrapper 


def user_directory_path(instance, filename):
    return '{0}/{0}'.format(instance.id, images_path(filename))


class Post(models.Model):
    title = models.CharField(max_length=30, unique=True, verbose_name="Title")
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(scrapsettings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_post')
    updated = models.DateTimeField(auto_now=True)
    content = models.TextField()
    brief = models.TextField(max_length=100, default='')
    created_on = models.DateTimeField(auto_now=True)
    pumps = models.ManyToManyField(ScrapUser, related_name='blog_post_pumps')
    status = models.IntegerField(choices=STATUS, default=0)
    phone_number = models.CharField(max_length=200, default='')
    email_address = models.CharField(max_length=200, default='')
    image1 = models.ImageField(upload_to='upload/{}'.format(user_directory_path), null=True, blank=True, default='')
    image2 = models.ImageField(upload_to='upload/{}'.format(user_directory_path), null=True, blank=True, default='')
    image3 = models.ImageField(upload_to='upload/{}'.format(user_directory_path), null=True, blank=True, default='')

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('posts:index')


    def number_of_pumps(self):
        self.pumps.count()



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    context = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)


    class Meta:

        ordering = ['date_created']
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
    
    def __str__(self):
        return 'Comment: {0} - {0}'.format(self.post.title, self.profile)



class SubComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='sub_comments')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    context = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)


    class Meta:

        ordering = ['date_created']
        verbose_name = 'sub_comment'
        verbose_name_plural = 'sub_comments'
    
    def __str__(self):
        return 'Sub_Comment: {0} - {0}'.format(self.comment.post.title, self.profile)

posts/views.py
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, ScrapUser, Comment
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from posts.create_post import CreatePostForm
from posts.create_user import CreateUserForm, EditUserForm, EstablishProfileForm
from posts.create_comment import CommentForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse
from django.views.decorators.clickjacking import xframe_options_exempt
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import send_mail, BadHeaderError
from django.http import JsonResponse
from django.db.models import Count 
from django.views.generic.edit import FormMixin 
from django.views.generic.detail import DetailView 



@xframe_options_exempt
def create_user(request):
    if request.method == 'POST':
        register_form = CreateUserForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            messages.success(request, "Account Created.")
            return redirect('posts:establish_profile')
    else:
        register_form = CreateUserForm
    return render(request=request, template_name="posts/create_user.html", context={"register_form": register_form})


@xframe_options_exempt
def create_userprofile(request):
    if request.method == 'POST':
        profile_form = EstablishProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_form.save(request)
            messages.success(request, "Account Created.")
            return redirect('posts:index')
    else:
        register_form = EstablishProfileForm()
    return render(request=request, template_name="posts/establish_profile.html", context={"profile_form": register_form})



@xframe_options_exempt
def login_user(request):
    if request.method == "POST":
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("posts:index")
            else:
                messages.error(request, "Invalid username and password")
        else:
            messages.error(request, "Invalid username and password")
    login_form = AuthenticationForm()
    return render(request=request, template_name="posts/login_user.html", context={"login_form": login_form})


@login_required
@xframe_options_exempt
def logout_user(request):
    logout(request)
    messages.info(request, "Logged out.")
    return redirect("posts:index")


@login_required
@xframe_options_exempt
def create_post(request):
    if request.method == 'POST':
        post_form = CreatePostForm(request.POST, request.FILES)

        if post_form.is_valid():
            fs = post_form.save(commit=False)
            fs.author = request.user
            fs.save()
            messages.success(request, "Post Created.")
            return redirect("posts:index")
        else:
            print(post_form.errors)
    else:
        post_form = CreatePostForm()
    return render(request=request, template_name="posts/create_post.html",
                  context={'post_form': post_form, })


@login_required
@xframe_options_exempt
def my_profile(request):
    logged_in_user = request.user
    page = request.GET.get('page', 1)
    my_posts = Post.objects.filter(author=logged_in_user)
    paginator = Paginator(my_posts, 5)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(paginator.num_pages)
    return render(request=request, template_name='posts/my_profile.html', context={"my_posts": pages})


class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = CreatePostForm
    template_name = 'posts/edit_post.html'


class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'

    def get_success_url(self, **kwargs):
        return reverse('posts:profile')


def get_user_ip(request):
    user_ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if user_ip:
        ip = user_ip.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    print(ip)


@login_required
@xframe_options_exempt
def succeed_edit_post(request):
    return render(request=request, template_name='posts/succeed_edit_post.html')



def pump(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    pumped = False
    if post.pumps.filter(id=request.user.id).exists():
        post.pumps.remove(request.user)
        pumped = False
    else:
        post.pumps.add(request.user)
        pumped = True

    return HttpResponseRedirect(reverse('posts:post_detail', args=[str(pk)]))



class PostList(generic.ListView):
    model = Post
    paginate_by = 15
    template_name = 'posts/index.html'
    queryset = Post.objects.filter(status=1,).order_by('-created_on')





class PostDetail(FormMixin, DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    form_class = CommentForm 

    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)

        data = get_object_or_404(Post, id=self.kwargs['pk'])
        pumped = False
        if data.pumps.filter(id=self.request.user.id).exists():
            pumped = True 

        context['pumped'] = pumped  
        context['coment_form'] = CommentForm(initial={'post': self.object})
        return context 

    def post(self, request, *args, **kwargs):
          self.object = self.get_object()
          comment_form = self.get_form()
          if comment_form.is_valid():
            return self.form_valid(comment_form)
          else:
            return self.form_invalid(comment_form)

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.profile_id = self.request.user.id 
        form.save()
        return super(PostDetail, self).form_valid(form)
                  


def create_comments(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('give_comment'))
    comments = post.comment.filter(active=True)
    new_comments = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comments = comment_form.save(commit=False)
            new_comments.post = post 
            new_comments.save()
    else:
        comment_form = CommentForm()
    
    return render(request, template_name='posts/post_detail.html', context=
    {'comments': comments,
     'new_comment': new_comments,
     'comment_form': comment_form, 
    })

def edit_profile(request):
    if request.method == 'POST':
        editform = EditUserForm(request.POST, instance=request.user)
        if editform.is_valid():
            editform.save()
            return redirect('posts:profile')
    else:
        editform = EditUserForm(instance=request.user)
    return render(request=request, template_name='posts/edit_profile.html', context={'form': editform})

def edit_profilepic(request):
    pass

class View_Profile(generic.DetailView):
    model = Post 
    template_name = 'posts/view_profile.html'



        




def delete_user(request):
    if request.method == 'POST':
        user = ScrapUser.objects.filter(username=request.user)
        user.delete()
        return redirect('posts:index')
    return render(request=request, template_name='posts/delete_user.html')


@xframe_options_exempt
def change_password(request):
    if request.method == 'POST':
        password_change_form = PasswordResetForm(request.POST)
        if password_change_form.is_valid():
            data = password_change_form.cleaned_data['email']
            scrap_user = ScrapUser.objects.filter(Q(email=data))
            if scrap_user.exists():
                for user in scrap_user:
                    subject = 'Change Your Password'
                    email_template_name = 'posts/password_change/password_reset_email.txt'
                    content = {
                        'email': user.email,
                        'domain': 'https://www.scrapnc.com',
                        'site_name': 'ScrapSite',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    scrap_email = render_to_string(email_template_name, content)
                    try:
                        send_mail(subject, scrap_email, 'ncscrapsite@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        messages.error('Invalid Header Found')
                    logout(request)
                    return redirect('password_reset_done')
    password_change_form = PasswordResetForm()

posts/templates/posts/base.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <head>
{% load bootstrap3 %}
{% load static %}
{% block css %}{% endblock css %}

{% block style %}{% endblock style %}


<link href="{% static 'posts/css/scrap_style.css' %}" rel="stylesheet"/>
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static 'bootstrap/css/custom.css' %}" rel="stylesheet" media="screen">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>


     <title> {% block title %} Scrap Post {% endblock %}</title>
  
     <div class="scrapnav"> 
     <nav class="navbar navbar-expand-lg navbar-dark bg-dar">
      <a class="navbar-brand" href="{% url 'posts:index' %}"><i class="fas fa-home">dumbbell</i></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% if user.is_authenticated %}

        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'posts:profile' %}"><span class="sr-only">(current)</span><i class="fas fa-user"> {{user.username}}</i></a>
          <a class="nav-item nav-link" href="{% url 'posts:create_post' %}"><i class="fas fa-pen">write post</i></a>
          <a class="nav-item nav-link" href="{% url 'posts:logout' %}"><i class="fas fa-sign-out-alt">logout</i></a>
        </div>

        {% else %}
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'posts:login' %}"><b>login</b></a>
          <a class="nav-item nav-link" href="{% url 'posts:create_user' %}"><b>signup</b></a>
        </div>
       {% endif %}
      </div>
    </nav>

    

  </div>


 </head>
<body>
<div id="wrap">
    <div id="main">
{% block content %}- {% endblock content %}
    </div>
</div>
<script>
window.onscroll = function() {myFunction()};

// Get the navbar
var navbar = document.getElementByClassName("scrapnav");

// Get the offset position of the navbar
var sticky = navbar.offsetTop;

// Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
</script>


</body>


 <footer>
     <div class="footer">
{% block footer %} - {% endblock footer %}
     </div>
 </footer>
</html>

posts/templates/posts/comment.html
<div class="modal fade" id="commentModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Comment Model content-->
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Give Comment</h4>
        </div>

        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

posts/templates/posts/index.html
{% extends "posts/base.html" %}
{% block css %}
{% load static %}
{% load bootstrap3 %}
<link href="{% static 'static/posts/css/scrap_style.css' %}" rel="stylesheet"/>
<link href="{% static 'posts/css/scrap_style.css' %}" rel="stylesheet"/>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

{% endblock css %}



{% block content %}



<style>
.pagination>li>a, .pagination>li>span { border-radius: 50% !important;margin: 0 5px;}

body {
            background-color: #ffffff;
        }

 .h7 {
            font-size: 0.8rem;
        }

 .gedf-wrapper {
            margin-top: 0.97rem;
        }

 .gedf-main {
                margin-left: auto;
                margin-right: auto;
                padding-left: 4rem;
                padding-right: 4rem;
                padding-top: 1rem;

            }
 .gedf-card {
                margin-bottom: 2.77rem;
            }

 .dropdown-toggle::after {
            content: none;
        }
















</style>
<div class="mainfeed">
     {% for post in post_list %}
     <div class="col-md-6 gedf-main">
                <div class="card gedf-card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    {% if post.author.profile.profile_pic %}
                                    <img style="width: 50px; height: 50px;"class="rounded-circle" width="45" src="{{ post.author.profile.profile_pic.url }}" alt="">
                                    {% else %}
                                    <img class="rounded-circle" width="45" src="https://img.icons8.com/ios/50/000000/gender-neutral-user.png" alt="">
                                    {% endif %} 
                                </div>
                                <div class="ml-2">
                                    <div class="h5 m-0"><a href="{% url 'posts:view_profile' post.id %}">{{ post.author.username }}</a></div>
                                </div>
                            </div>
                            <div>

                            </div>
                        </div>



                    </div>
                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>{{ post.created_on }}</div>
                        <a class="card-link" href="{% url 'posts:post_detail' post.id %}">
                            <h5 class="card-title"> {{ post.title }}</h5>
                        </a>

                        <p class="card-text">
                            {{ post.brief }}
                        </p>
                    </div>
                     <div class="card-footer">
                        <div class="pump_button">
                         <a class="card-link"><i class="fa fa-dumbbell"> {{post.pumps.count}}</i> </a>
                        </div>
                    </div>


                </div>

            </div>
     {% endfor %}
</div>










{% endblock content %}

{% block footer %}
{% if is_paginated %}
<div class="footer">
<nav aria-label="Page navigation example">
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
       <li class="active"><span> {{ i }}<span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a class="page-link" href="?page={{i}}">{{i}}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}

</ul>
</nav>
</div>
{% endif %}
{% endblock footer %}

posts/templates/posts/my_profile.html
{% extends "posts/base.html" %}
{% block css %}
{% load static %}
{% load bootstrap3 %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="{% static 'static/posts/css/scrap_style.css' %}" rel="stylesheet"/>
<link href="{% static 'posts/css/scrap_style.css' %}" rel="stylesheet"/>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

{% endblock css %}
{% block content %}

<style>

body {
            background-color: #ffffff;
        }

        .h7 {
            font-size: 0.8rem;
        }

        .gedf-wrapper {
            margin-top: 0.97rem;
        }

        .gedf-main {
                padding-left: 4rem;
                padding-right: 4rem;
                padding-top: 4rem;
                margin-left: auto;
                margin-right: auto;
            }
            .gedf-card {
                margin-bottom: 2.77rem;
            }

        /**Reset Bootstrap*/
        .dropdown-toggle::after {
            content: none;
        }






</style>




<div class="col-md-6 gedf-main">
    <div class="card gedf-card" style="border-radius: 0px 10px 10px 10px;">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                   
                </div>
                <div>

                </div>
        </div>
        <div class="card-body">

            <p class="card-text">
                <h4> <a href="{% url 'posts:change_password' %}">Change Password</a></h4>
                <h4>  <a href="{% url 'posts:edit_user' %} ">Change EmailAddress</a></h4>
                <h4> <a href="{% url 'posts:delete_user' %}">Delete Account</a></h4>
                <h4> <a href="{% url 'posts:edit_profilepic' %}">Edit Profile Pic</a></h4>            </p>
        </div>
    </div>

</div>

<hr/>

<div class="mainfeed">
    {% for posts in my_posts %}

     <div class="col-md-6 gedf-main">

                <div class="card gedf-card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    {% if posts.author.profile.profile_pic %}
                                    <img style="width: 50px; height: 50px;"class="rounded-circle" width="45" src="{{ posts.author.profile.profile_pic.url }}" alt="">
                                    {% else %}
                                    <img class="rounded-circle" width="45" src="https://img.icons8.com/ios/50/000000/gender-neutral-user.png" alt="">
                                    {% endif %} 
                                </div>
                                <div class="ml-2">
                                    <div class="h5 m-0">{{ posts.author.username }}</div>
                                </div>
                            </div>
                            <div>

                            </div>
                        </div>



                    </div>
                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>{{ posts.created_on }}</div>
                        <a class="card-link" href="{% url 'posts:post_detail' posts.id %}">
                            <h5 class="card-title"> {{ posts.title }}</h5>
                        </a>

                        <p class="card-text">
                            {{ posts.content }}
                        </p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'posts:edit_post' posts.pk %}" class="card-link">Edit</a>
                        <a href="{% url 'posts:delete_post' posts.pk %}" class="card-link">Delete</a>
                        <a href="#" class="card-link">Share</a>
                    </div>
                </div>

            </div>
     {% endfor %}
</div>

{% endblock content %}

{% block footer %}
{% if my_posts.has_other_pages %}
<div class="footer">
<nav aria-label="Page navigation example">
<ul class="pagination">
    {% if my_posts.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ my_posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}

    {% for i in my_posts.paginator.page_range %}
    {% if my_posts.number == i %}
       <li class="page-item active"><span> {{ i }}<span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a class="page-link" href="?page={{i}}">{{i}}</a></li>
    {% endif %}
    {% endfor %}

    {% if my_posts.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ my_posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}

</ul>
</nav>
</div>
{% endif %}
{% endblock footer %}